# This file will be included by the Makefile under the project directory.

FLOAT_O := $(FLOAT:.a=.o)
FLOAT_VFPRINTF_O := $(dir $(FLOAT))FLOAT_vfprintf.o

FLOAT_A_OBJ := $(FLOAT_O) $(FLOAT_VFPRINTF_O)

$(FLOAT): $(FLOAT_A_OBJ)
	@mkdir -p $(@D)
	ar r $@ $^

# TODO: complete the following rules

$(FLOAT_O): lib-common/FLOAT/FLOAT.c
	@mkdir -p $(@D)
	$(CC) -c $< -o $@ -Ilib-common -m32 -O2 -fno-if-conversion -fno-builtin

$(FLOAT_VFPRINTF_O): lib-common/FLOAT/FLOAT_vfprintf.c
	@mkdir -p $(@D)
	$(CC) -c $< -o $@ -Ilib-common -m32 -O2 -fno-if-conversion -fno-builtin -fno-stack-protector -D_FORTIFY_SOURCE=0
